### ISSUE TITLE
[BUG] Ray's actor construction is broken in docstring

### ISSUE THREAD

**Issue by sergiovalmac** [pytorch/rl#1862]
## To Reproduce

Steps to reproduce the behavior.

This is a minimal example to reproduce the bug - it's been taken from the docstrings in `collectors/distributed/ray.py` :
```python

from torch import nn
from tensordict.nn import TensorDictModule
from torchrl.envs.libs.gym import GymEnv
from torchrl.collectors.collectors import SyncDataCollector
from torchrl.collectors.distributed import RayCollector


def env_maker():
    return GymEnv("Pendulum-v1", device="cpu")


policy = TensorDictModule(nn.Linear(3, 1), in_keys=["observation"], out_keys=["action"])

distributed_collector = RayCollector(
    create_env_fn=[env_maker],
    policy=policy,
    collector_class=SyncDataCollector,
    max_frames_per_traj=50,
    init_random_frames=-1,
    reset_at_each_iter=-False,
    collector_kwargs={
        "device": "cpu",
        "storing_device": "cpu",
    },
    num_collectors=1,
    total_frames=10000,
    frames_per_batch=200,
)
for i, data in enumerate(distributed_collector):
    if i == 2:
        print(data)
        break
```
Error messages and stack trace:
```bash
C:\Users\me\code\torchrl> python .\sample_envs.py
C:\Users\me\venvs\3_10\lib\site-packages\gymnasium\core.py:311: UserWarning: WARN: env.num_envs to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.num_envs` for environment variables or `env.get_wrapper_attr('num_envs')` that will search the reminding wrappers.
  logger.warn(
C:\Users\me\venvs\3_10\lib\site-packages\gymnasium\core.py:311: UserWarning: WARN: env.reward_space to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.reward_space` for environment variables or `env.get_wrapper_attr('reward_space')` that will search the reminding wrappers.
  logger.warn(
2024-02-01 00:11:48,502 INFO worker.py:1621 -- Started a local Ray instance.
Traceback (most recent call last):.\ 
File "C:\Users\me\code\torchrl\sample_envs.py", line 53, in <module>
    distributed_collector = RayCollector(
  File "C:\Users\me\venvs\3_10\lib\site-packages\torchrl\collectors\distributed\ray.py", line 463, in __init__
    self.add_collectors(
  File "C:\Users\me\venvs\3_10\lib\site-packages\torchrl\collectors\distributed\ray.py", line 548, in add_collectors
    cls = self.collector_class.as_remote(remote_config).remote
  File "C:\Users\me\venvs\3_10\lib\site-packages\torchrl\collectors\distributed\ray.py", line 87, in as_remote
    remote_collector = ray.remote(**remote_config)(cls)
  File "C:\Users\me\venvs\3_10\lib\site-packages\ray\_private\worker.py", line 2872, in _make_remote
    return ray.actor._make_actor(function_or_class, options)
  File "C:\Users\me\venvs\3_10\lib\site-packages\ray\actor.py", line 1372, in _make_actor
    return ActorClass._ray_from_modified_class(
  File "C:\Users\me\venvs\3_10\lib\site-packages\ray\actor.py", line 490, in _ray_from_modified_class
    self.__ray_metadata__ = _ActorClassMetadata(
  File "C:\Users\me\venvs\3_10\lib\site-packages\ray\actor.py", line 362, in __init__
    self.method_meta = _ActorClassMethodMetadata.create(
ature.py", line 54, in get_signature
    return inspect.signature(func)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 3254, in signature       
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 3002, in from_callable   
    return _signature_from_callable(obj, sigcls=cls,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 2401, in _signature_from_callable
    sig = _get_signature_of(obj.__func__)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 2536, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'types.GenericAlias'>
```

## Expected behavior

The script should run without error when making the remote actors.

## System info
OS: Windows 11

Virtual environment
* Python 3.10.11
* torch==2.2.0
* torchrl==0.3.0
* numpy==1.26.3

The error happens both installing torchrl with pip or from source.

```python
>>> import torchrl, numpy, sys
>>> print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.3.0 1.26.3 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] win32
```

## Checklist

- [ X ] I have checked that there is no similar issue in the repo (**required**)
- [ X ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [ X ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by albertbou92** [comment]
I am able to reproduce the bug. Let me look into it.

**Comment by albertbou92** [comment]
I have been further able to reproduce the bug with some code that does involve TorchRL. 

```
import ray
from torch.utils.data import IterableDataset


class SyncDataCollector(IterableDataset):
    def __iter__(self):
        return


ray.init()
ray.remote(SyncDataCollector)
```

**Comment by albertbou92** [comment]
https://github.com/ray-project/ray/issues/42914

**Comment by sergiovalmac** [comment]
I tried with python 3.8 and I don't get the GenericAlias issue, but I got a different error:
```bash
2024-02-12 20:29:01,299 INFO worker.py:1724 -- Started a local Ray instance.
Traceback (most recent call last):
  File "sample_envs.py", line 55, in <module>
    distributed_collector = RayCollector(
  File "3.8_torchrl\lib\site-packages\torchrl\collectors\distributed\ray.py", line 475, in __init__
    ray.wait(object_refs=pending_samples)
  File "3.8_torchrl\lib\site-packages\ray\_private\auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "3.8_torchrl\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
TypeError: wait() got an unexpected keyword argument 'object_refs'
```

**Comment by albertbou92** [comment]
I was able to reproduce the error. `Ray` changed the signature of `ray.wait()` in recent versions. This PR(https://github.com/pytorch/rl/pull/1908/files) fixes the problem. With it the code runs without errors. Thanks a lot for pointing out the error. 

I will monitor the open issue in the official Ray repository for any updates aimed at resolving compatibility issues with newer Python versions.

**Comment by vmoens** [comment]
@albertbou92 Should we close this or is there anything outstanding?

**Comment by albertbou92** [comment]
I would keep the issue open until https://github.com/ray-project/ray/issues/42914 is solved

**Comment by sergiovalmac** [comment]
I confirmed the PR fixed the issue for python 3.8! Thanks!

**Comment by albertbou92** [comment]
The issue is fixed now after merging https://github.com/pytorch/rl/pull/2015. It works with python > 3.8

**Comment by sergiovalmac** [comment]
Nice, thanks so much! I confirm it works with python3.9 and python3.10 :-)
