### ISSUE TITLE
[BUG] SACTrainer and CQLTrainer unnecessarily query collector environments

### ISSUE THREAD

**Issue by aswanth-07** [pytorch/rl#4376]
## Problem

`SACTrainer` and `CQLTrainer` read `full_action_spec_unbatched` from the collector whenever the loss has no explicit `action_spec`. That lookup is unnecessary when a numeric `target_entropy` already determines the entropy target or when the actor already carries the action spec.

Collectors that do not expose `getattr_env` therefore cannot construct either trainer even though the loss has all information it needs.

This is the SAC/CQL follow-up requested in the review of #4368.

## Reproduction

A loss with an explicit target works independently:

```python
loss = SACLoss(actor, qvalue, target_entropy=0.0)
assert loss.target_entropy == 0.0
```

Passing the same loss to `SACTrainer` with a collector that implements the ordinary trainer collector methods but has no `getattr_env` currently fails during construction:

```text
AttributeError: 'Collector' object has no attribute 'getattr_env'
```

`CQLTrainer` fails at the equivalent lookup. The same failure occurs with `target_entropy="auto"` when the actor already has a valid action spec.

## Expected behavior

Both trainers should use an already-resolved numeric target or the actor's action spec without querying the collector environment. The existing collector lookup should remain available when SAC uses automatic target entropy and neither the loss nor actor has an action spec.

## Proposed scope

- Restrict the collector action-spec lookup to unresolved automatic target entropy.
- Cover numeric and actor-spec resolution for both trainers through their public constructors.
- Preserve and test SAC's collector fallback.

## Checklist

- [x] I checked open and closed issues and pull requests for overlapping SAC/CQL trainer, target entropy, action-spec, and `getattr_env` changes.
