### PR TITLE
[BugFix] Avoid unnecessary SAC and CQL collector spec queries

### LINKED ISSUE #4376: [BUG] SACTrainer and CQLTrainer unnecessarily query collector environments
## Problem

`SACTrainer` and `CQLTrainer` read `full_action_spec_unbatched` from the collector whenever the loss has no explicit `action_spec`. That lookup is unnecessary when a numeric `target_entropy` already determines the entropy target or when the actor already carries the action spec.

Collectors that do not expose `getattr_env` therefore cannot construct either trainer even though the loss has all information it needs.

This is the SAC/CQL follow-up requested in the review of #4368.

## Reproduction

A loss with an explicit target works independently:

```python
loss = SACLoss(actor, qvalue, target_entropy=0.0)
assert loss.target_entropy == 0.0
```

Passing the same loss to `SACTrainer` with a collector that implements the ordinary trainer collector methods but has no `getattr_env` currently fails during construction:

```text
AttributeError: 'Collector' object has no attribute 'getattr_env'
```

`CQLTrainer` fails at the equivalent lookup. The same failure occurs with `target_entropy="auto"` when the actor already has a valid action spec.

## Expected behavior

Both trainers should use an already-resolved numeric target or the actor's action spec without querying the collector environment. The existing collector lookup should remain available when SAC uses automatic target entropy and neither the loss nor actor has an action spec.

## Proposed scope

- Restrict the collector action-spec lookup to unresolved automatic target entropy.
- Cover numeric and actor-spec resolution for both trainers through their public constructors.
- Preserve and test SAC's collector fallback.

## Checklist

- [x] I checked open and closed issues and pull requests for overlapping SAC/CQL trainer, target entropy, action-spec, and `getattr_env` changes.

### PR DESCRIPTION
**Pull request by aswanth-07**
## Description

`SACTrainer` and `CQLTrainer` now query the collector environment for an action spec only when automatic target entropy cannot be resolved from the loss or actor.

Numeric `target_entropy` values and actor-provided action specs no longer require `collector.getattr_env`. SAC's existing collector fallback remains unchanged when neither the loss nor actor supplies the required spec.

The regression constructs both trainers through their public APIs with a collector that has no environment accessor. It covers explicit zero target entropy and automatic entropy derived from a two-dimensional actor spec, then verifies the resolved target. A separate case verifies that SAC still requests the collector spec exactly once and resolves the same two-dimensional target to `-2.0`.

## Motivation and Context

Closes #4376.

This is the SAC/CQL follow-up requested during review of #4368. Collectors without `getattr_env` currently fail during trainer construction even when the loss already has enough information to determine target entropy.

- [x] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Tests

- `python -m pytest test/test_trainer.py::TestEntropyTrainerActionSpec test/objectives/test_sac.py test/objectives/test_cql.py -q -k 'EntropyTrainerActionSpec or test_sac_target_entropy_auto or test_sac_target_entropy_explicit or test_cql_target_entropy_auto'` (`25 passed`, `2894 deselected`)
- Repository hooks for line endings, formatting, flake8, pydocstyle, pyupgrade, codespell, autoflake, and docstring placement passed on the three changed files.
- `py -3.13 scripts/check-docstring-args torchrl/trainers/algorithms/sac.py torchrl/trainers/algorithms/cql.py` passed.
- The full test suite was not run locally.

## Checklist

- [x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

AI assistance disclosure: AI-assisted development tools were used during investigation and implementation. The reported tests were run against the final diff.

### CODE REVIEW

**Comment by aswanth-07** [comment]
Rebased this onto current main in 65600d12 and resolved the trainer test import overlap. The focused SAC/CQL trainer regression remains green: 25 passed, 2894 deselected. Changed-file formatting, lint, pydocstyle, pyupgrade, codespell, autoflake, and docstring-argument checks also pass.

**Review by vmoens — APPROVED** [review]
Good catch thanks!
